languageCode = "es"
languageName = "Spanish"
languageDirection = "ltr"
#displayName = ":es:"
#isoCode = "es"
weight = 2
#rtl = false

title = "Williams Orellana"

copyright = "Hecho con :heart: en El Salvador, &copy; Derechos Reservados 2024"

[params]
   dateFormat = "2 January 2006"
   description = "~/home/worellana"
   #autor.name = "Williams Orellana"

[params.author]
  name = "Williams Orellana"
  image = "img/Williams.jpg"
  headline = "Solo otro desarrollador en Internet"
  bio = "Introvertido y en ocaciones asocial üö∂‚Äç‚ôÇÔ∏è, Ingeniero de Software üíª, apasionado por la tecnolog√≠a üë®‚Äçüíª, Entusiaste de la ciberseguridad üêâ, Software Libre üêß, amante de las mascotas üêï, a√∫n aprendiendo a vivir. :coffee:"
  links = [
   { email = "mailto:hi@williamsorellana.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/worellana" },
     { gitlab = "https://gitlab.com/worellana" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://instagram.com/williamsorellana" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/williamsorellana" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/worellana" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
     { x-twitter = "https://twitter.com/worellana" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  ]
